# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lowerTriOuterProduct_cpp <- function(vec) {
    .Call(`_ellipsoidgaussian_lowerTriOuterProduct_cpp`, vec)
}

logTransGradAdjust_cpp <- function(invSig, invSig_jaco) {
    .Call(`_ellipsoidgaussian_logTransGradAdjust_cpp`, invSig, invSig_jaco)
}

calcPsdMat_linvSig_jaco_cpp <- function(invSig, psdMat_grad, lambda) {
    .Call(`_ellipsoidgaussian_calcPsdMat_linvSig_jaco_cpp`, invSig, psdMat_grad, lambda)
}

calcVec_linvSig_jaco_cpp <- function(invSig, vec_grad, lambda, centered_sdat) {
    .Call(`_ellipsoidgaussian_calcVec_linvSig_jaco_cpp`, invSig, vec_grad, lambda, centered_sdat)
}

calc_linvSig_grad_cpp <- function(invSig, psdMat_grad, vec_grad, lambda, centered_sdat) {
    .Call(`_ellipsoidgaussian_calc_linvSig_grad_cpp`, invSig, psdMat_grad, vec_grad, lambda, centered_sdat)
}

calc_lambda_grad_MatPart2_cpp <- function(lambda, psdMat_grad, invSigma) {
    .Call(`_ellipsoidgaussian_calc_lambda_grad_MatPart2_cpp`, lambda, psdMat_grad, invSigma)
}

calc_lambda_grad_VecPart_cpp <- function(invSigma, centered_sdat, vec_grad) {
    .Call(`_ellipsoidgaussian_calc_lambda_grad_VecPart_cpp`, invSigma, centered_sdat, vec_grad)
}

calc_lambda_grad_cpp <- function(lambda, psdMat_grad, vec_grad, invSigma, centered_sdat) {
    .Call(`_ellipsoidgaussian_calc_lambda_grad_cpp`, lambda, psdMat_grad, vec_grad, invSigma, centered_sdat)
}

armaMatMult <- function(A, B) {
    .Call(`_ellipsoidgaussian_armaMatMult`, A, B)
}

eigenMatMult <- function(A, B) {
    .Call(`_ellipsoidgaussian_eigenMatMult`, A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_ellipsoidgaussian_eigenMapMatMult`, A, B)
}

calcgradLambdaprior_cpp <- function(Lambda, phi, kappa) {
    .Call(`_ellipsoidgaussian_calcgradLambdaprior_cpp`, Lambda, phi, kappa)
}

rotate_cpp <- function(a, b) {
    .Call(`_ellipsoidgaussian_rotate_cpp`, a, b)
}

kfb_cpp <- function(j, gam, lam, ta) {
    .Call(`_ellipsoidgaussian_kfb_cpp`, j, gam, lam, ta)
}

saddle_equat_cpp <- function(ta, gam, lam) {
    .Call(`_ellipsoidgaussian_saddle_equat_cpp`, ta, gam, lam)
}

reorder_vec <- function(v, idx) {
    .Call(`_ellipsoidgaussian_reorder_vec`, v, idx)
}

root4SaddleEquat <- function(gam, lam, low, up) {
    .Call(`_ellipsoidgaussian_root4SaddleEquat`, gam, lam, low, up)
}

findFBconst_cpp <- function(gam, lam, which_, ordered) {
    .Call(`_ellipsoidgaussian_findFBconst_cpp`, gam, lam, which_, ordered)
}

approxFBconst_cpp <- function(para1, para2, idx_) {
    .Call(`_ellipsoidgaussian_approxFBconst_cpp`, para1, para2, idx_)
}

Vech2Mat_cpp <- function(para2_vech) {
    .Call(`_ellipsoidgaussian_Vech2Mat_cpp`, para2_vech)
}

calclogPseudoconst_MatParGrad4_cpp <- function(para2_vech, para1) {
    .Call(`_ellipsoidgaussian_calclogPseudoconst_MatParGrad4_cpp`, para2_vech, para1)
}

